### ISSUE TITLE
XCOPY changes the timestamp of some files

### ISSUE THREAD

**Issue by joshux** [FDOS/xcopy#8]
This is a duplicate of [https://sourceforge.net/p/freedos/bugs/29/](url)
I had tried the xcopy version from fdos 1.3 and also compiled with watcom, both get the same problem.

I digged in to the code a bit and found the problem is likely in shared.inc:
```
// Line 556
setftime(fileno(dest_file), &filetime);  

// Line 93
return((_dos_setftime(handle,ftm.msc_time.date,ftm.msc_time.time) == 0) ? 0 : -1); 
```

Watcom's documentation didn't specify that _dos_setftime could take on a POSIX file descriptor. I've independently tested it and doesn't work either.

**Comment by PerditionC** [comment]
your assessment appears correct; the POSIX file descriptors that fileno() return from stream (fopen(), ...) based descriptors need further conversion to OS file#s via _os_handle() function.  I believe this resolves the issue but have no definitive test case so please reopen if it still occurs.
